Brewfile, README.md, db/setup.js, script/bootstrap, script/server, script/setup
From http://githubengineering.com/scripts-to-rule-them-all this makes the setup easier.
I also cleaned up the README with a little markdown :tophat: :sparkles:
=> Update setup to make the process more streamlined

db/users.js, public/javascripts/userModel.js, routes/users.js, views/user.handlebars
Right now, any user id at the end of url will log into authenticated user. Also fixed floating point with total spending in usermodel :shipit:
=> Cleans up validation of logged in user. 

views/login.handlebars, views/signup.handlebars
Submit buttons on login and signup page now reacts to keyup events rather than change events. Form gets validated on every keystroke
=> Form validation

config.js, db/setup.js, db/users.js, handlers/UserHandler.js, routes/routes.js, routes/users.js, script/setup
* Whitespace (spaces instead of tabs)
* Update db_name to `spending_tracker_development` cause it makes more sense
* Fix setup script
=> Some fixes

.travis.yml
@atareshawty this is just the starter file, your tests don't run using `npm test` so I have no idea what to do
=> Set the app up for CI

README.md
=> Fixing readme through a separate branch... @tarebyte

config.js, db/testUserSetup.js, db/users.js, handlers/UserHandler.js, server.js, test/dbTest.js
Changed get user request handler to not blindly request new spending data from the db unless the query actual has filter parameters. Added null checking in the two methods under test
=> Added testing around db methods findByUsername and insertTransaction

config.js, db/users.js, test/dbTest.js
All methods that pass info into db check for correct type and specs of input passed
=> Added input validation in db interaction methods and tests around them

db/users.js, public/javascripts/helpers/login.js, public/javascripts/helpers/signup.js, public/javascripts/helpers/user/category.js, public/javascripts/helpers/user/dateFilter.js, public/javascripts/helpers/user/transaction.js, views/login.handlebars, views/signup.handlebars, views/user.handlebars
Js that was previously in views now moved to separate files
=> Cleaned up client side jquery!

db/setup.js
More than one category can't be added for a single id
=> Added id and category pair unique constraint into table categories

views/signup.ejs
Spent 5 minutes wondering what I was doing wrong
=> email -> username

public/javascripts/helpers/user/dateFilter.js
Missed a cosmetic change in last PR
=> Filtered dates are cleared when submit button is hit

.gitignore, Procfile, Procfile.dev, README.md, config.js, db/users.js, script/server
A few configuration things are needed to get it up and running on aws ec2 ubuntu instance
=> [WIP] Get AWS working

public/javascripts/app.js, public/javascripts/helpers/user/transaction.js
When a new chart is build, the existing canvas is replaced with a new one, then the new one gets painted on. When a purchase is added, a new chart gets built
=> Repaint pie chart when new spending is added

public/javascripts/helpers/user/category.js
In response to https://github.com/atareshawty/SpendingTracker/issues/40 
The fix was hardly a line. I added a check for duplicate categories so it doesn't get added @kylekthompson
=> Issue40 custom categories not showing

controllers/SessionsController.js, controllers/UsersController.js, package.json, public/javascripts/helpers/signup.js, routes/routes.js, server.js, views/login.ejs, views/signup.ejs
Addition of flash message when either signup or login fails
=> Issue43 flash messages

public/javascripts/app.js, views/handlebars_templates/user_template.handlebars
Add things back when spending is entered. It looks like this with no spending:
=> Add blankslate and remove table when user spending array is blank 

public/javascripts/app.js, public/javascripts/userFetch.js, public/stylesheets/style.css, views/401.ejs, views/handlebars_templates/user_template.handlebars, views/home.ejs, views/login.ejs, views/needLogin.ejs, views/signup.ejs, views/user.ejs, views/users.ejs
Add Primer's grid layout to all pages and style the forms on the profile page.
This should close #46.
See here:
=> Clean up styling

views/home.ejs
For another webhook test on the ec2 instance
=> Changed message on home page

config.js, controllers/UsersController.js, public/javascripts/app.js, public/javascripts/helpers/user/dateFilter.js, public/javascripts/helpers/user/transaction.js, public/javascripts/userFetch.js, public/stylesheets/style.css, views/handlebars_templates/income_tracker_template.handlebars, views/handlebars_templates/user_template.handlebars, views/partials/tab.ejs
Added income tracking! The UI got moved around some. In addition to the spending chart and table, there's an income table and comparison chart for both spending and income.
=> Issue53 income tracking

public/javascripts/app.js, public/stylesheets/style.css, views/handlebars_templates/income_tracker_template.handlebars
If not, don't and you don't get the gross scroll bar
=> If spending table is larger than 8, add scrolling

public/javascripts/app.js
The color depends on the balance
=> Added comparison column on income/spending bar chart 

public/javascripts/helpers/user/category.js, public/javascripts/helpers/user/dateFilter.js, public/javascripts/helpers/user/transaction.js
when either spending is entered or date filter button is hit or new category is added
=> Added scrolling back to top of page

public/javascripts/user/transaction.js
Made money regex for purchase validation more strict. It forces the inclusion of decimal value. ex) 3000 doesn't pass --> 3000.00 does
=> Fix Purchase Cost

public/stylesheets/grid.css, public/stylesheets/style.css, views/partials/head.ejs
Looks a little better on mobile
=> @tarebyte css magik
